meta_product_name: "Green Thumb"
meta_title: "Green Thumb - Your digital assistant for happy plants"
meta_description: "App for tech-savvy plant lovers with busy lives who need to organize their plant care routines. Green Thumb enables you to access information about plants in an easy way and get reminders for care tasks."
meta_image: "cover.png"
